branch-defaults:
  main:
    environment: django-example-dev
    group_suffix: null
environment-defaults:
  django-example-dev:
    branch: null
    repository: null
global:
  application_name: django-example
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
