branch-defaults:
  master:
    environment: djangoexample_prod_env
  develop:
    environment: djangoexample_dev_env
global:
  application_name: djangoexample
  default_platform: Python 3.8
  default_region: ap-southeast-1
  profile: null
  sc: git